### ISSUE TITLE
Texlive 2016 reports deprecated commands

### ISSUE THREAD

**Issue by aquadr** [josephwright/biblatex-phys#15] opened 2016-08-18 12:21 UTC
Texlive 2016 reports the usage of deprecated commands in this style.

I get the warnings

````
Package biblatex Warning: \mkbibnamefirst is deprecated, please use \mkbibnamegiven. Using \mkbibnamegiven.

Package biblatex Warning: \mkbibnamelast is deprecated, please use \mkbibnamefamily. Using \mkbibnamefamily.

Package biblatex Warning: \mkbibnameaffix is deprecated, please use \mkbibnamesuffix. Using \mkbibnamesuffix.

Package biblatex Warning: \mkbibnamefirst is deprecated, please use \mkbibnamegiven. Using \mkbibnamegiven.

Package biblatex Warning: \mkbibnamelast is deprecated, please use \mkbibnamefamily. Using \mkbibnamefamily.

Package biblatex Warning: \mkbibnameaffix is deprecated, please use \mkbibnamesuffix. Using \mkbibnamesuffix.
````
using pdfTeX 3.14159265-2.6 and biber version: 2.5

Minimal example
```
\documentclass[]{article}
\usepackage{hyperref}
\usepackage[style=phys]{biblatex}
\addbibresource{lib.bib}

\begin{document}

\cite{ref}

\printbibliography

\end{document}
```
```
@article{ref,
  title = {Title},
  author = {Firstname Lastname and Lastname, Firstname},
  date = {2000-01-01}
}
```

**Comment by josephwright** [comment] 2016-08-18 12:48
Dupe of https://github.com/josephwright/biblatex-phys/issues/13.

**Closed by josephwright** 2016-08-18 12:48 UTC
